### SURROUNDS ###
require-module surrounds
map global user s ': enter-user-mode surrounds<ret>' -docstring "Surround mode"
map global user S ': enter-user-mode surrounds-undo<ret>' -docstring "Surround mode (delete)"

### FZF ###
require-module fzf
require-module fzf-file
map global user f ': fzf-mode<ret>' -docstring 'FZF mode'

### COLORS ###
colorscheme gruvbox-dark

### LSP ###
eval %sh{kak-lsp --kakoune -s $kak_session}  # Not needed if you load it with plug.kak.
lsp-enable

add-highlighter global/ number-lines
add-highlighter global/ show-whitespaces -lf '~' -tab '|' -tabpad '-' -indent '|'
add-highlighter global/ show-matching

lsp-auto-hover-enable
set global lsp_hover_max_info_lines 10
set global lsp_hover_max_diagnostic_lines 10

map global user l %{:enter-user-mode lsp<ret>} -docstring "LSP mode"
map global insert <tab> '<a-;>:try lsp-snippets-select-next-placeholders catch %{ execute-keys -with-hooks <lt>tab> }<ret>' -docstring 'Select next snippet placeholder'
map global object a '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object <a-a> '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object e '<a-semicolon>lsp-object Function Method<ret>' -docstring 'LSP function or method'
map global object k '<a-semicolon>lsp-object Class Interface Struct<ret>' -docstring 'LSP class interface or struct'
map global object d '<a-semicolon>lsp-diagnostic-object --include-warnings<ret>' -docstring 'LSP errors and warnings'
map global object D '<a-semicolon>lsp-diagnostic-object<ret>' -docstring 'LSP errors'

remove-hooks global lsp-filetype-python
hook -group lsp-filetype-python global BufSetOption filetype=python %{
	set-option buffer lsp_servers %{
		[pyright-langserver]
		root_globs = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json", ".git", ".hg"]
		args = ["--stdio"]
	}
}

hook global BufSetOption filetype=gdscript %{
    set-option buffer lsp_servers %{
        [gdscript]
        filetypes = ["gdscript"]
        root_globs = [".import"]
        command = "nc"
        args = ["localhost", "6005"]
    }
}

### CUSTOM TMUX ###
define-command tmux-kak-horizontal -params 1.. -docstring '
tmux-kak-horizontal <command> [<arguments>]: create a new kakoune client as a tmux pane
The current pane is split into two, left and right
The kakoune command is executed in a new client' \
%{
    tmux-terminal-horizontal kak -c %val{session} -e "%arg{@}"
}
complete-command tmux-kak-horizontal command
alias global vs tmux-kak-horizontal

define-command tmux-kak-vertical -params 1.. -docstring '
tmux-kak-vertical <command> [<arguments>]: create a new kakoune client as a tmux pane
The current pane is split into two, left and right
The kakoune command is executed in a new client' \
%{
    tmux-terminal-vertical kak -c %val{session} -e "%arg{@}"
}
complete-command tmux-kak-vertical command
alias global sp tmux-kak-vertical

map -docstring "xml tag objet" global object t %{c<lt>([\w.]+)\b[^>]*?(?<lt>!/)>,<lt>/([\w.]+)\b[^>]*?(?<lt>!/)><ret>}

### HIGHLIGHTING ###

# hook global BufCreate .*\.ino$ %{ set buffer filetype arduino }

### MISC ###
set global tabstop 3

hook global WinCreate '.*' %{ noexpandtab }
hook global WinCreate '.*/.kakrc' %{ set window filetype kak }

hook global WinSetOption filetype=python %{ expandtab; set window softtabstop 4 }
hook global WinSetOption filetype=yaml %{ expandtab; set window softtabstop 2; set window indentwidth 2 }
hook global WinSetOption filetype=haskell %{ expandtab; set window softtabstop 2; set window indentwidth 2 }

### SYSTEM-SPECIFIC CONFIGS ###
eval %sh{
	if [ -n "$HOSTNAME" -a -f "$kak_config/systems/$HOSTNAME/kakrc" ]; then
		echo "source '$kak_config/systems/$HOSTNAME/kakrc'"
	fi
}

eval %sh{
	if [ -n "$HOSTNAME" -a -f "$kak_config/systems/$HOSTNAME/kakrc" ]; then
		echo "source '$kak_config/systems/$HOSTNAME/kakrc'"
	fi
}

eval %sh{
	(
		c=$PWD
		echo "$c"
		while [ "$c" != '/' ]; do
			c=$(dirname "$c")
			echo "$names$c"
		done
	) | tac | while read line; do
		[ -e "$line/.kakrc" ] && echo "source $line/.kakrc"
	done
}

